name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t my-hugo-site .

      - name: Login to Harbor
        run: |
          echo "${{ secrets.HARBOR_PASSWORD }}" | docker login harbor.ismyfavorite.au --username ${{ secrets.HARBOR_USERNAME }} --password-stdin

      - name: Tag Docker image
        run: |
          docker tag my-hugo-site harbor.ismyfavorite.au/library/my-hugo-site:latest

      - name: Push Docker image to Harbor
        run: |
          docker push harbor.ismyfavorite.au/library/my-hugo-site:latest
